### ISSUE TITLE
Include weathermap plug-in

### ISSUE THREAD

**Issue by natm** [setiseta/docker-librenms#23]
Please can the LibreNMS Weather map plug-in be included in the build.

https://github.com/librenms-plugins/Weathermap

This would be a great addition to the container!

**Comment by setiseta** [comment]
whats wrong with the way in readme?

**Comment by RalfHerzog** [comment]
Just setting `WEATHERMAP=1` does it for me. As I see, the manual checkout as stated under "Plugins" in the readme.md is not necessary. I think it can be removed.
Additionally the plugin repo is cloned from [seti/Weathermap](https://github.com/setiseta/Weathermap). What's the benefit checking out that instead of the original repo from [librenms-plugins/Weathermap](https://github.com/librenms-plugins/Weathermap)?

**Comment by setiseta** [comment]
there are some changes to wokr with the container and the plugin mounted directory outside of the webdir.

**Comment by natm** [comment]
working well many thanks
