### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'librenms'@'192.168.32.3' (using password: NO)

### ISSUE THREAD

**Issue by oniondada** [setiseta/docker-librenms#36]
Hi Author
After runing docker-compose up -d, I meet the issue (as title).

**Comment by setiseta** [comment]
Can you Post your docker-compose.yml (remove sensible data please)

**Comment by oniondada** [comment]
I only modify tz to Asia/Taipei

version: '3'

services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=pwd4librenms
      - MYSQL_DATABASE=librenms
      - TZ=Asia/Taipei
    restart: always

  librenms:
    build: .
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 8081:80
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=pwd4librenms
     - TZ=Asia/Taipei
      - POLLER=24
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
      - SYSLOG_ENABLED=1
    restart: always

**Comment by setiseta** [comment]
Since upsteam default config changed, it need some update on this repo.
For a quick fix you can add the connection data to your config:
File: data/config/config.php
```
### Database config
$config['db_host'] = "mysql";
$config['db_user'] = "root";
$config['db_pass'] = "pwd4librenms";
$config['db_name'] = "librenms";
```

At the end i suggest you to use the official librenms docker.
It can be found here: https://github.com/librenms/docker
This should be a more complete and actual repo, since I'm also testing it, and if all works I will use it for myself, and this one will be deprecated.

**Comment by oniondada** [comment]
got it, thanks
